name: CI Pipeline

# El workflow se ejecuta en cada push y pull_request hacia la rama main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout del código fuente
    - name: Checkout código
      uses: actions/checkout@v4
    
    # Configurar JDK 17
    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    # Cache de dependencias de Maven para mejorar el rendimiento
    - name: Cache dependencias Maven
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    # Ejecutar las pruebas
    - name: Ejecutar pruebas unitarias
      run: mvn clean test
    
    # Generar reporte de cobertura (opcional)
    - name: Generar reporte de cobertura
      run: mvn jacoco:report
      continue-on-error: true
    
    # Subir resultados de pruebas
    - name: Publicar resultados de pruebas
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Resultados de Pruebas Maven
        path: target/surefire-reports/*.xml
        reporter: java-junit